services:

  db: 
    build: .
    image: draw-code/postgres
    restart: unless-stopped
    shm_size: 128mb
    env_file: "postgres.env"
    volumes: 
        - drawdata:/var/lib/postgresql/data
    ports:
        - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  drawdata:
