services:
  c-compiler:
    build: .
    image: c-compiler
    read_only: true
    network_mode: "none"
    pids_limit: 64
    mem_limit: 256m
    cpus: "0.5"
    tmpfs:
      - /tmp:size=32m,nosuid,nodev,exec
    volumes: 
      - type: bind
        source: /home/rasc/hosts/draw-code/packages/express_backend_app/dist/model/sandbox/c/
        target: /usr/src/code/c/usercode/
        read_only: true


