services:
  js-compiler:
    build: .
    image: js-compiler
    network_mode: "none"
    pids_limit: 64
    mem_limit: 256m
    volumes: 
      - type: bind
        source: /home/r-amarthya-sreechand/Web_Dev/leetcode_project/packages/express_backend_app/src/model/sandbox/js/
        target: /usr/src/code/js/readonly/
        read_only: true


